guillo16/miranda

app/models/answer.rb, app/models/answer_user.rb, app/models/bookmark.rb, app/models/question.rb, app/models/user.rb, app/models/video.rb, app/views/pages/home.html.erb, config/environments/development.rb, db/migrate/20181119201332_create_videos.rb, db/migrate/20181119203056_create_bookmarks.rb, db/migrate/20181119203344_create_questions.rb, db/migrate/20181119203957_create_answers.rb, db/migrate/20181119204506_create_answer_users.rb, db/migrate/20181119205131_add_score_to_user.rb, db/schema.rb, test/models/answer_test.rb, test/models/answer_user_test.rb, test/models/bookmark_test.rb, test/models/question_test.rb, test/models/video_test.rb
add devise 
add all models
test in rails console
=> add all the models and validation

config/routes.rb, test/controllers/answers_controller_test.rb
=> update the routes

app/views/shared/_navbar.html.erb
add some icons to the navbar
add the log out in mobile version
=> change icons of the navbar

app/views/shared/_navbar.html.erb
=> repair navbar issue

app/views/shared/_footer.html.erb
=> add links to footer

app/views/videos/index.html.erb, db/schema.rb, db/seeds.rb
add two seeds
add index videos
=> Videoindex

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_index_video.scss, app/views/videos/index.html.erb
=> incomplete index

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_index_video.scss, app/views/videos/index.html.erb
make the index video page 
change the btn danger in bootstrap
=> make the index page

app/views/shared/_navbar.html.erb, app/views/users/show.html.erb
change the env file 
make the edit image works
=> fix cloudinary

app/assets/stylesheets/pages/_index_video.scss, app/views/videos/index.html.erb
=> change the index

app/views/videos/show.html.erb
=> correct videos show

app/views/shared/_navbar.html.erb, app/views/users/edit_profile.html.erb, app/views/users/show.html.erb
=> fix navbar

app/models/user.rb
=> correct the mailchip error

app/assets/stylesheets/pages/_index_video.scss, app/controllers/videos_controller.rb, app/views/videos/index.html.erb
=> filters added

app/controllers/videos_controller.rb, app/models/video.rb, app/views/videos/index.html.erb, app/views/videos/show.html.erb, db/migrate/20181126135455_add_region_to_video.rb, db/schema.rb, db/seeds.rb
add the filters to video index
add column region to video
add the region seed
=> Indexvideo

app/assets/stylesheets/pages/_index_video.scss, app/views/videos/index.html.erb, db/seeds.rb
=> Dictionary

app/assets/stylesheets/pages/_video.scss, app/controllers/bookmarks_controller.rb, app/controllers/users_controller.rb, app/controllers/videos_controller.rb, app/models/bookmark.rb, app/policies/bookmark_policy.rb, app/views/bookmarks/create.js.erb, app/views/bookmarks/destroy.js.erb, app/views/bookmarks/update.js.erb, app/views/videos/show.html.erb, config/application.rb, config/routes.rb, db/migrate/20181126191642_add_checked_to_bookmarks.rb, db/schema.rb
Bookmarks now work using AJAX, therefore no reloading of the page.
=> Better bookmarks

app/assets/stylesheets/pages/_users.scss, app/views/users/show.html.erb
=> updated bookmarks in the user show section

app/javascript/packs/application.js, app/javascript/packs/translate.js, app/views/videos/show.html.erb
create dictionary for transcript
=> dictionary finish

app/assets/stylesheets/pages/_users.scss, app/controllers/bookmarks_controller.rb, app/policies/bookmark_policy.rb, app/views/bookmarks/destroy.js.erb, app/views/bookmarks/update.js.erb, app/views/users/show.html.erb, app/views/videos/show.html.erb, config/routes.rb
Bookmarks can now be deleted via AJAX from the user show section.
=> improved bookmarks functionality

app/assets/stylesheets/pages/_index_video.scss, app/views/videos/index.html.erb, app/views/videos/show.html.erb
=> change index style

db/seeds.rb
=> add some seeds

app/assets/stylesheets/pages/_index_video.scss
=> change card description

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_index_challenge.scss, app/controllers/challenges_controller.rb, app/models/answer.rb, app/models/answer_user.rb, app/models/challenge.rb, app/models/question.rb, app/models/video.rb, app/views/challenges/index.html.erb, app/views/videos/index.html.erb
=> Challengeindex

app/assets/stylesheets/pages/_index_challenge.scss, app/views/challenges/index.html.erb
=> Stylechallenge

app/assets/stylesheets/pages/_index_challenge.scss, app/policies/challenge_policy.rb, app/views/challenges/index.html.erb, app/views/shared/_navbar.html.erb
=> Challenges
